ENV_TO_ID = {
    # Known tasks
    "dmc_walker_stand-v1": 0,
    "dmc_walker_walk-v1": 1,
    "dmc_reacher_easy-v1": 2,
    "dmc_cheetah_run-v1": 3,
    "dmc_finger_spin-v1": 4,
    "pen-v0": 5,
    "relocate-v0": 6,
    "assembly-v2-goal-observable": 7,
    "bin-picking-v2-goal-observable": 8,
    "button-press-topdown-v2-goal-observable": 9,
    "drawer-open-v2-goal-observable": 10,
    "hammer-v2-goal-observable": 11,
    # Unknown tasks
    "button-press-wall-v2-goal-observable": 12,
    "button-press-topdown-wall-v2-goal-observable": 13,
    "faucet-open-v2-goal-observable": 14,
    "faucet-close-v2-goal-observable": 15,
    "door-open-v2-goal-observable": 16,
    "door-close-v2-goal-observable": 17,
    "drawer-close-v2-goal-observable": 18,
    "window-close-v2-goal-observable": 19,
    "peg-insert-side-v2-goal-observable": 20,
    "plate-slide-v2-goal-observable": 21,
    "plate-slide-back-v2-goal-observable": 22,
    "plate-slide-back-side-v2-goal-observable": 23,
    "handle-press-v2-goal-observable": 24,
    "handle-press-side-v2-goal-observable": 25,
    "push-back-v2-goal-observable": 26,
}

ENV_TO_SUITE = {
    # Known tasks
    "dmc_walker_stand-v1": "dmc",
    "dmc_walker_walk-v1": "dmc",
    "dmc_reacher_easy-v1": "dmc",
    "dmc_cheetah_run-v1": "dmc",
    "dmc_finger_spin-v1": "dmc",
    "pen-v0": "adroit",
    "relocate-v0": "adroit",
    "assembly-v2-goal-observable": "metaworld",
    "bin-picking-v2-goal-observable": "metaworld",
    "button-press-topdown-v2-goal-observable": "metaworld",
    "drawer-open-v2-goal-observable": "metaworld",
    "hammer-v2-goal-observable": "metaworld",
    # Unknown tasks
    "button-press-wall-v2-goal-observable": "metaworld",
    "button-press-topdown-wall-v2-goal-observable": "metaworld",
    "faucet-open-v2-goal-observable": "metaworld",
    "faucet-close-v2-goal-observable": "metaworld",
    "door-open-v2-goal-observable": "metaworld",
    "door-close-v2-goal-observable": "metaworld",
    "drawer-close-v2-goal-observable": "metaworld",
    "window-close-v2-goal-observable": "metaworld",
    "peg-insert-side-v2-goal-observable": "metaworld",
    "plate-slide-v2-goal-observable": "metaworld",
    "plate-slide-back-v2-goal-observable": "metaworld",
    "plate-slide-back-side-v2-goal-observable": "metaworld",
    "handle-press-v2-goal-observable": "metaworld",
    "handle-press-side-v2-goal-observable": "metaworld",
    "push-back-v2-goal-observable": "metaworld",
}
